### ISSUE TITLE
src/fairy-juice.h emits a warning upon compilation

### ISSUE THREAD

**Issue by irced** [Elronnd/libport#1]
# In file included from src/port.c:
`src/fairy-juice.h: warning: backslash-newline at end of file`

# recommendation: write make-fairy-juice.p6 to linebreak the last line as follows
`my $text = 'static char * const MAGIC_FAIRY_JUICE = "'`;
`$text ~= "src/support.p6".IO.lines.join(Q:c|\n\{"\n"}|);`
`$text ~= '";\qq"\n"';`
`spurt "src/fairy-juice.h", $text;`

**Comment by moon-chilled** [comment]
Will probably do this once I'm able to make any progress at all on the project.  Currently blocked by [this](https://github.com/rakudo/rakudo/issues/3173).

**Comment by moon-chilled** [comment]
Fixed in 969fb065bfec6b3c011e5648606da608558b4be6.  Actually it was 'fixed' before that, but I kept the ticket open because make-fairy-juice wasn't very clean.
